### ISSUE TITLE
"tlsv1 alert unknown ca" errors with the indigodatacloud/im Docker image

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/im#224]
IM, running using the indigodatacloud/im Docker image, is able to successfully deploy VMs on some EGI FedCloud sites, e.g. CESNET-MetaCloud. However some other sites, e.g. SCAI and INFN-PADOVA-STACK, I get errors like this:
```
Cloud Provider Error: Error querying the OCCI server: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)
```
Note that I can instantiate VMs on these sites using https://dashboard.appdb.egi.eu/vmops (which from the log messages appears to use IM underneath). Another site (RECAS-BARI) gives a similar error:
```
Cloud Provider Error: Error obtaining Keystone v2 Token: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)
```
FYI I'm using the current image (pulled today).

**Comment by micafer** [comment]
Hi @alahiff,

This error is usually related with the python requests library.
But I cannot reproduce the error.
I have tested these sites with the last version of the docker image (1.6.7) and I do not get this error:
In particular these sites works for me:
CESNET-MetaCloud
INFN-PADOVA-STACK

These sites are failing but with other error message:
SCAI -> Error obtaining Keystone v2 Token: 401 Client Error: Not Authorized for url: https://fc.scai.fraunhofer.de:5000//v2.0/tokens
RECAS-BARI -> Error obtaining Keystone v2 Token: 401 Client Error: Not Authorized for url: https://cloud.recas.ba.infn.it:5000/v2.0/tokens

In fact I have tested the OCCI client with these two sites and they are also failing with a similar error.

**Comment by alahiff** [comment]
Hi @micafer, Ignoring the sites giving keystone errors, using indigodatacloud/im:1.6.7 I still get the error:
```
Cloud Provider Error: Error querying the OCCI server: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590)
```
for INFN-PADOVA-STACK, SCAI and IISAS-FEDCLOUD. But CESNET-MetaCloud is fine. For testing this I've just been using a very simple RADL like this:
```
network public (outbound = 'yes')

system node (
instance_type = '1' and
net_interface.0.connection = 'public' and
net_interface.0.dns_name = 'testnode' and
disk.0.os.name='linux' and
disk.0.image.url= 'https://egi-cloud.pd.infn.it:8787/948d9e74-d203-4fb0-b49b-8df9cf3f479e' and
disk.0.os.credentials.username='centos'
)

deploy node 1
```
I'm using OCCI VOMS auth data (I'm not sure where to get a token from to use the OCCI OIDC auth data).

**Comment by micafer** [comment]
Hi @alahiff,

 I'm not able to reproduce the error. Using the docker image "indigodatacloud/im:1.6.7" and the same radl that you have shown in the comment I can make it work.

The VM are correctly created I only get an error trying to get a public IP:
```IP allocation over quota in pool ext-net.```

> I'm using OCCI VOMS auth data (I'm not sure where to get a token from to use the OCCI OIDC auth data).
Almost all sites uses OCCI voms auth. Currently As far as I know there are no OCCI OIDC auth sites in production. 
The error shown with keystone tokens is raising when the IM uses the voms auth mechanism to get a keystone token with openstack sites.

**Comment by alahiff** [comment]
Could it be that these sites haven't installed the full set of trust anchors, and therefore won't accept my proxy? My grid certificate is from the UK eScience CA.

**Comment by micafer** [comment]
Could you try to access this sites using the rOCCI client?

**Comment by alahiff** [comment]
Same problem:
```
FATAL -- : [rOCCI-cli] An SSL error occurred! Please, make sure your credentials are valid and recognized by the endpoint! Message: SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: tlsv1 alert unknown ca
```
so clearly not IM's fault. Thanks for your help anyway. Time to submit some GGUS tickets I guess...

**Comment by micafer** [comment]
Hi @alahiff,

It seems that this problem was related with an error in some VOMS servers.
It has been fixed and now it should work.

**Comment by alahiff** [comment]
Unfortunately I still get the same error at all the affected sites.

**Comment by alahiff** [comment]
FYI I finally worked out what was wrong - I hadn't been using an RFC 3820 compliant proxy.
